### ISSUE TITLE
Do not download old sources

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/docker-builder#1]
Looks like download_sources.sh downloads all sources from abf.yml

removed_sources:
  lzo-2.06.tar.gz: a11768b8a168ec607750842bbef406f11547b904
  lzo-2.07.tar.gz: 3051f622f8898c41f673955cb8e449e774c6ccc5
sources:
  lzo-2.08.tar.gz: 64c3e44843a44ffc4533aa89e41516f42bfefa76

Files between sections removed_sources: and sources: must not be downloaded, to reduce impact on network.

**Comment by berolinux** [comment]
Same goes for "abb restore"...

Out of curiosity, does anything actually use removed_sources: or should we just get rid of any removed_sources in .abf.yml?

**Comment by dsilakov** [comment]
I vote for "get rid". We can always use git history to get old sources and I don't know any other tool that relies on removed_sources.

**Comment by berolinux** [comment]
me too

**Comment by tpgxyz** [comment]
Check for "sources:" is needed here
https://github.com/OpenMandrivaSoftware/docker-builder/blob/master/download_sources.sh#L8

**Comment by fedya** [comment]
Patches welcome here!

**Comment by tpgxyz** [comment]
First .abf.yml should be parsed with 
sed -e '1,/^[Ss]ources:$/d'

somehow output of this needs to be parsed with https://github.com/OpenMandrivaSoftware/docker-builder/blob/master/download_sources.sh#L8

I did not figure out how to do this in sed onliner without pipes etc.

**Comment by tpgxyz** [comment]
I prepared this, please review #2
