### ISSUE TITLE
Test are wrong

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/docker-builder#11]
Tests claims
run rpmdev-vercmp 0:19.1.1-2 0:19.1.1-2
Package lib64GL-devel is either the same, older, or another problem. Extra tests failed

Which is wrong
https://abf.openmandriva.org/build_lists/567144

New build of mesa and tests claims that package is alreaady in repos, which is not true.

**Comment by tpgxyz** [comment]
Second there is no test.log if i run "Rerun tests" from ABF.

**Comment by fedya** [comment]
can't reproduce
look here
build before bump release
https://abf.openmandriva.org/build_lists/567687
build after bump release
https://abf.openmandriva.org/build_lists/567691

In first case test failed
in second passed just like expected, please make sure that bug persist.

**Comment by tpgxyz** [comment]
Looks good now.
