### ISSUE TITLE
No re-tries when repo got changed

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/docker-builder#12]
See here:
https://abf.openmandriva.org/build_lists/574940

```
[MIRROR] lib64clangSema9-9.0.0-0.20190709.1-omv4000.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 2184548 but expected size is: 2868580
[FAILED] lib64clangSema9-9.0.0-0.20190709.1-omv4000.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
Error: Error downloading packages:
  Cannot download lib64clangSema9-9.0.0-0.20190709.1-omv4000.x86_64.rpm: All mirrors were tried
```

**Comment by fedya** [comment]
It's fixed already.
i just haven't access to predator and tawern builders to redeploy it.

**Comment by tpgxyz** [comment]
@fedya Sorry it is not working https://abf.openmandriva.org/build_lists/575004

**Comment by fedya** [comment]
@tpgxyz as i said before it is server-tawern-2.openmandriva.org
I can't restart builder there, issue is fixed day ago.

**Comment by tpgxyz** [comment]
@fedya  this is c64 https://abf.openmandriva.org/build_lists/575016

**Comment by fedya** [comment]
letfover builder
dropped

**Comment by fedya** [comment]
fixed

**Comment by tpgxyz** [comment]
Thanks
