### ISSUE TITLE
package test failed

### ISSUE THREAD

**Issue by AngryPenguinPL** [OpenMandrivaSoftware/docker-builder#14]
Test failed for this package: https://abf.openmandriva.org/build_lists/583082

Test was repeated twice and only what I see is:
```
No match for argument: /home/omv/digikam/digikam.rpmlintrc
Error: Unable to find a match: /home/omv/digikam/digikam.rpmlintrc
```
All packages from here are installable. I checked by downloading and installing them manually.

**Comment by fedya** [comment]
culrpit here https://github.com/OpenMandrivaSoftware/docker-builder/blob/master/build-rpm.py#L404

**Comment by fedya** [comment]
fixed
