### ISSUE TITLE
Add to blacklist 

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaSoftware/docker-builder#16]
It seems we need to add to blacklist:

1. Qt5 package stack
2. KFrameworks package stack
3. Plasma desktop package stack
4 KApps package stack
5. LXQt package stack

The reason is these need to be built in a specific order to work and we *think* that auto updating these in ABF is corrupting that order. So the idea is that we will do each group with bero's scripts.

I don't know for sure how to do this so I'll leave it to those that do.

**Comment by benbullard79** [comment]
There are package lists for all 5 of those here:
https://github.com/OpenMandrivaSoftware/kde-packaging-tools

**Comment by benbullard79** [comment]
For qt:
openmandriva/qt5-qtbase
openmandriva/qt5-qtdeclarative
openmandriva/qt5-qtxmlpatterns
openmandriva/qt5-qtscript
openmandriva/qt5-qtsvg
openmandriva/qt5-qtmultimedia
openmandriva/qt5-qttools
openmandriva/qt5-qtdoc
openmandriva/qt5-qtquickcontrols openmandriva/qt5-qtquickcontrols2 openmandriva/qt5-qtlocation openmandriva/qt5-qtimageformats openmandriva/qt5-qtgraphicaleffects openmandriva/qt5-qtconnectivity openmandriva/qt5-qtx11extras openmandriva/qt5-qtserialport openmandriva/qt5-qtsensors openmandriva/qt5-qtwayland openmandriva/qt5-qtwebsockets
openmandriva/qt5-qtwebchannel
openmandriva/qt5-qtwebengine
openmandriva/qt5-qttranslations openmandriva/qt5-qt3d openmandriva/qt5-qtlottie openmandriva/qt5-qtwebview openmandriva/qt5-qtvirtualkeyboard openmandriva/qt5-qtspeech openmandriva/qt5-qtscxml openmandriva/qt5-qtremoteobjects openmandriva/qt5-qtpurchasing openmandriva/qt5-qtnetworkauth openmandriva/qt5-qtgamepad openmandriva/qt5-qtdatavis3d openmandriva/qt5-qtcharts openmandriva/qt5-qtwebglplugin openmandriva/qt5-qtserialbus

**Comment by benbullard79** [comment]
I don't have time to do anymore at the moment.

**Comment by fedya** [comment]
@benbullard79 it was much much wasy than you thought

https://github.com/OpenMandrivaSoftware/docker-builder/commit/1cb7768a6778318d9415d91a20412df9913f8a38
