### ISSUE TITLE
Incorrect regexp for specs

### ISSUE THREAD

**Issue by mikhailnov** [OpenMandrivaSoftware/docker-builder#25]
Scripts try to process `br-rhel.spec.in` from https://abf.io/import/libstdc++-gcc10 and build fails  https://abf.io/build_lists/3402514

**Comment by Gel0bmstu** [comment]
Should be closed

**Comment by mikhailnov** [comment]
You could write in the description of the commit https://github.com/OpenMandrivaSoftware/docker-builder/commit/58120f00887cfec4cfc3213f853c1e64de15aff1 : 

```
Fixes: https://github.com/OpenMandrivaSoftware/docker-builder/issues/25
```

then this issue would have closed automatically

Thanks
