### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/docker-builder#3]
Implement tests:
- [x] Freshly build RPM can be installed
- [x] Freshly build SRPM can be installed
- [x] Re-run tests
- [x] Check if same or newer version of package exists in repository

**Comment by fedya** [comment]
Good points, Tomasz, need to discuss how to implement it.

**Comment by tpgxyz** [comment]
I have some ideas, i'll prepare pull request soon.

**Comment by tpgxyz** [comment]
Ok first test is done.

I wonder if testing SRPMS is really needed ?

In case of last one test i found it is going to be hard task to compare EVRD using plain bash functions.

@fedya @DuratarskeyK @berolinux  guys wdyt ?

**Comment by DuratarskeyK** [comment]
There's a special tool for that somewhere

**Comment by tpgxyz** [comment]
@DuratarskeyK  tool for comparing EVRD ? Well we can use python-rpm but, question is "maybe there is a chance to compare EVRD using pure bash functions :+1: "

**Comment by DuratarskeyK** [comment]
From what I remember, it's complicated. At least that's what Jeff says.

**Comment by Conan-Kudo** [comment]
use `rpmdev-vercmp` ;)

**Comment by tpgxyz** [comment]
@Conan-Kudo  Yes, we will try

**Comment by tpgxyz** [comment]
Finally last check is done. Closing
