### ISSUE TITLE
src.rpm files are missing

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/docker-builder#9]
Looks like src.rpm files are missing from build_id

See here:
https://abf.openmandriva.org/build_lists/567144

**Comment by fedya** [comment]
https://github.com/OpenMandrivaSoftware/docker-builder/blob/master/build-rpm.py#L190
issue here
will fix it soon

**Comment by fedya** [comment]
fixed in https://github.com/OpenMandrivaSoftware/docker-builder/commit/3fb78dc81a2ca9b32b1fb20c18c87074254071cf

**Comment by tpgxyz** [comment]
Thanks
